### ISSUE TITLE
[Feat] CardView 를 구현합니다

### ISSUE THREAD

**Issue by chldudqlsdl** [DeveloperAcademy-POSTECH/MacC-Team3-BluePeriodClub#11]
### 📝 작업 목적 / Miro / Figma

CardView 를 구현합니다

---

### 🛠️ Tasks

* [ ] CardView에서 사용할 모델을 만듭니다
* [ ] CardView의 화면 뷰를 구현합니다
* [ ] CardView의 로직을 구현합니다
