### ISSUE TITLE
[Chore] 기타 수정 사항

### ISSUE THREAD

**Issue by eratchacha** [DeveloperAcademy-POSTECH/MacC-Team3-BluePeriodClub#120]
### 📝 작업 목적 / Miro / Figma

1차 병합 이후 발견한 기타 수정 사항들을 반영합니다. 
---

### 🛠️ Tasks

* [x] 탭바 아이콘 변경
* [x] Common Mistake 카드 사이즈 변경
* [x] Collection View 카드 vertical padding 변경
* [x] Collection View 받침 파트 추가 및 UI 개선
* [x] LearningView BackButton 사용성 개선
