### ISSUE TITLE
[Fix] 기타 수정 사항 수정 

### ISSUE THREAD

**Issue by eratchacha** [DeveloperAcademy-POSTECH/MacC-Team3-BluePeriodClub#150]
### 📝 작업 목적 / Miro / Figma

남은 수정사항들을 수정합니다.
---

### 🛠️ Tasks

* [ ] 다크 모드 적용 시 instruction view navigation
* [x] instruction view text 추가
* [ ] learning view navigation animation 수정
