### ISSUE TITLE
[Feat] 앱 심사 제출 전 최종 수정 사항

### ISSUE THREAD

**Issue by eratchacha** [DeveloperAcademy-POSTECH/MacC-Team3-BluePeriodClub#157]
### 📝 작업 목적 / Miro / Figma

앱 심사 제출 전 최종적으로 수정합니다.
---

### 🛠️ Tasks

* [ ] 한글 폰트 볼드 적용하기
* [ ] Same Card Collection Quiz View
* [ ] Vowel Drawing View 길이
* [ ] ㄱ,ㄴ,ㄷ,ㄹ 퀴즈 이후 앱이 강제 종료됨
* [ ] 음성 파일들 중 없는 파일 존재
* [ ] LearningView Divider 위아래 동일하게 수정
* [ ] Pracitice View Dividier Padding 수정하기
* [ ] 추가 예정
