### ISSUE TITLE
[Feat] 음성 듣기 관련 기능을 수선합니다

### ISSUE THREAD

**Issue by chldudqlsdl** [DeveloperAcademy-POSTECH/MacC-Team3-BluePeriodClub#158]
### 📝 작업 목적 / Miro / Figma

음성 듣기 관련 기능을 수선합니다

---

### 🛠️ Tasks

* [ ] 온보딩 ㅏ, ㅜ 듣기
* [ ] 자음, 모음 예시단어 소리 넣기
* [ ] 모음 글씨 쓰기에 소리 넣기
* [ ] 프랙티스 소리 넣기
