### ISSUE TITLE
[Refactor] 비행 전 화면 리팩토링

### ISSUE THREAD

**Issue by eratchacha** [DeveloperAcademy-POSTECH/MacC-Team3-BluePeriodClub#45]
### 📝 작업 목적 / Miro / Figma

- TripDateSettingView의 Date Picker 변수 로직 수정
- 다크모드 지원을 위한 비행 전 화면 Background 구현 방법 수정
- FlightInfoSubmitView의 항공편 코드 입력 시 엔터 기능 추가
- FlightInfoConfirmVIew의 출발지/도착지 구현 방법 변경
- 파일 디렉토리 변경과 불필요한 파일 삭제

---

### 🛠️ Tasks

* [x] TripDateSettingView DatePicker Logic 수정
* [x] 다크모드 지원을 위한 Background 구현 방법 수정
* [ ] FlightSubmitView의 항공편 코드 엔터 입력 기능 추가
* [x] FlightConfrimView의 출발지, 도착지 구현 방법 변경
* [x] Views 내 디렉토리 추가 및 불필요한 ContentView, Model,Extension, ViewModel 삭제
